# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-06 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password1', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('mobile', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('loc', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
            ],
        ),
    ]
