# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-02 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpapp', '0005_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='dob',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
