# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-03 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('loc', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Emp',
        ),
        migrations.AlterField(
            model_name='customer',
            name='student',
            field=models.ManyToManyField(to='mtmapp.Student'),
        ),
    ]
