# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-03 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtmapp', '0003_auto_20181203_2006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student1',
            new_name='Students',
        ),
    ]
