# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-25 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PyShell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PyShell.Student'),
        ),
    ]
