# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-25 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PyShell', '0002_auto_20190125_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='oppertunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.CharField(max_length=50)),
                ('softwareDev', models.CharField(max_length=50)),
                ('softwareTest', models.CharField(max_length=50)),
                ('softwareAnal', models.CharField(max_length=50)),
                ('softwareDebug', models.CharField(max_length=50)),
                ('softwareMaint', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PyShell.Student')),
            ],
        ),
    ]
