# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-31 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('feedback', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('User_Name', models.CharField(max_length=50)),
                ('Password1', models.CharField(max_length=50)),
                ('Password2', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Mobile', models.BigIntegerField()),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Mobile', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=50)),
                ('startdate', models.DateField()),
                ('cources', multiselectfield.db.fields.MultiSelectField(choices=[('ui', 'UI'), ('django', 'DJANGO'), ('python', 'PYTHON'), ('restapi', 'RESTAPI')], max_length=100)),
                ('trainer', multiselectfield.db.fields.MultiSelectField(choices=[('nani', 'NANI'), ('prakash', 'PRAKASH'), ('raj', 'RAJ'), ('narayana', 'NARAYANA')], max_length=100)),
                ('timing', multiselectfield.db.fields.MultiSelectField(choices=[('evening', 'EVENING'), ('afternoon', 'AFTERNOON'), ('morning', 'MORNING')], max_length=100)),
            ],
        ),
    ]
