# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-31 11:37
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='cources',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('restapi', 'RESTAPI'), ('django', 'DJANGO'), ('python', 'PYTHON'), ('ui', 'UI')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='timing',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('evening', 'EVENING'), ('morning', 'MORNING'), ('afternoon', 'AFTERNOON')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='trainer',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('prakash', 'PRAKASH'), ('raj', 'RAJ'), ('narayana', 'NARAYANA'), ('nani', 'NANI')], max_length=100),
        ),
    ]
