# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-01 07:19
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0004_auto_20190101_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='cources',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('django', 'DJANGO'), ('python', 'PYTHON'), ('ui', 'UI'), ('restapi', 'RESTAPI')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='timing',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('evening', 'EVENING'), ('afternoon', 'AFTERNOON'), ('morning', 'MORNING')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='trainer',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('nani', 'NANI'), ('prakash', 'PRAKASH'), ('raj', 'RAJ'), ('narayana', 'NARAYANA')], max_length=100),
        ),
    ]
