# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-01 09:28
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0005_auto_20190101_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='cources',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ui', 'UI'), ('restapi', 'RESTAPI'), ('python', 'PYTHON'), ('django', 'DJANGO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='trainer',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('narayana', 'NARAYANA'), ('nani', 'NANI'), ('prakash', 'PRAKASH'), ('raj', 'RAJ')], max_length=100),
        ),
    ]
