# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-01 09:40
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0006_auto_20190101_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='cources',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ui', 'UI'), ('python', 'PYTHON'), ('restapi', 'RESTAPI'), ('django', 'DJANGO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='timing',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('evening', 'EVENING'), ('morning', 'MORNING'), ('afternoon', 'AFTERNOON')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='trainer',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('prakash', 'PRAKASH'), ('nani', 'NANI'), ('narayana', 'NARAYANA'), ('raj', 'RAJ')], max_length=100),
        ),
    ]
