# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-01 11:31
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0007_auto_20190101_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='cources',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ui', 'UI'), ('python', 'PYTHON'), ('django', 'DJANGO'), ('restapi', 'RESTAPI')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='timing',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('afternoon', 'AFTERNOON'), ('evening', 'EVENING'), ('morning', 'MORNING')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='trainer',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('narayana', 'NARAYANA'), ('raj', 'RAJ'), ('nani', 'NANI'), ('prakash', 'PRAKASH')], max_length=100),
        ),
    ]
