# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-05 06:27
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0008_auto_20190101_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='cources',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('restapi', 'RESTAPI'), ('ui', 'UI'), ('django', 'DJANGO'), ('python', 'PYTHON')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='timing',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('morning', 'MORNING'), ('evening', 'EVENING'), ('afternoon', 'AFTERNOON')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='trainer',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('nani', 'NANI'), ('raj', 'RAJ'), ('narayana', 'NARAYANA'), ('prakash', 'PRAKASH')], max_length=100),
        ),
    ]
