# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-25 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('customer_name', models.CharField(max_length=256)),
                ('customer_number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taskapp.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_size', models.IntegerField()),
                ('product_price', models.BigIntegerField()),
                ('product_active', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taskapp.Product'),
        ),
    ]
