# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-31 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=20)),
                ('cname', models.CharField(max_length=20)),
                ('cost', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
                ('mfgdate', models.DateField()),
            ],
        ),
    ]
