# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-27 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('order_name', models.CharField(help_text='Order Name', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ownapp.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(default=100, max_length=11, primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='Product name', max_length=250)),
                ('product_size', models.FloatField()),
                ('product_price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ownapp.Product'),
        ),
    ]
