# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-03 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakerapp', '0002_remove_employeedata_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedata',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employeedata',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
