# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-25 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many2oneapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('fee', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='courses',
            name='cfee',
        ),
    ]
