# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-09 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0002_auto_20181009_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phote',
            field=models.ImageField(max_length=200, upload_to='images'),
        ),
    ]
